insert into CURRENCY(id,COUNTRYCODE, CONVERSIONVALUE) values (1001, 'USD', 65);
insert into CURRENCY(id,COUNTRYCODE, CONVERSIONVALUE) values (1002, 'EUR', 75);
insert into CURRENCY(id,COUNTRYCODE, CONVERSIONVALUE) values (1003, 'RID', 55);
